### ISSUE TITLE
Removing 'account' from connection parameters to connect

### ISSUE THREAD

**Issue by adnobc** [snowflakedb/dplyr-snowflakedb#10]
Wasn't able to connect to SF instance. Removed line 225-226 from src-snowflakedb.R, and it works fine. 
https://github.com/snowflakedb/dplyr-snowflakedb/blob/7aa6646c8ac0b88bb385993140c37b72c5f7ec04/R/src-snowflakedb.R#L225-L226
Couldn't find what/if something needed to be specified this way to the JDBC driver, as it wasn't described in the driver documentation. (Using  JDBC driver version 3.6.22. Will try with an older driver to check if this has changed)

```
my_db <- src_snowflakedb(user = "user02",
                         password = "password1234",
                         account = "company.eu-central-1",
                         opts = list(role = "ROLEY",
                                     warehouse = "LARGE_WAREHOUSE",
                                     db = "BIG_DB",
                                     schema = "STAGEW"
                                     ))
```

**Comment by adnobc** [comment]
Okay... sorry. So alternative (probably easier solution) was to specify the full hostadress and for account just specify the account name (without region). In hindsight quite similair to #9 (the same). Anyway, for reference purpases, below the connection setup I used; with eu-central instance, explicit specification of host, role, warehouse, db and schema

```
my_db <- src_snowflakedb(user = "<user02>",
                         password = "password1234",
                         account = "company",
                         host = "company.eu-central-1.snowflakecomputing.com",
                         opts = list(role = "ROLEY",
                                     warehouse = "LARGE_WAREHOUSE",
                                     db = "BIG_DB",
                                     schema = "STAGEW"
                                     ))
```

**Comment by bluetyson** [comment]
Thanks for that.
