### ISSUE TITLE
SELECT * FROM "..." AS "zzz2" LIMIT 0

### ISSUE THREAD

**Issue by aaronbarnett** [snowflakedb/dplyr-snowflakedb#11]
I've got a connection setup between RStudio and Snowflake.  When I initiate a table view I receive and error.

> sessions = tbl(sf, "sessionview")

Error in .verify.JDBC.result(r, "Unable to retrieve JDBC result set for ",  : 
  Unable to retrieve JDBC result set for SELECT * FROM "sessionview" AS "zzz2" LIMIT 0 (SQL compilation error:
Object '"sessionview"' does not exist.)

If I run `SELECT * FROM "sessionview" AS "zzz2" LIMIT 0` in snowflake it fails because it does not like the quotes.  The modified query `SELECT * FROM sessionview AS "zzz2" LIMIT 0` runs fine in snowflake.

How can I get dplr to not use quotes on the table name?

R-3.4.3
snowflake-jdbc-3.6.9.jar
windows 10

**Comment by aaronbarnett** [comment]
Heard back from SF support...

>> Having the table name in quotes makes it case sensitive. All the table names are usually stored in UPPER CASE 

confirmed: works with table names in all caps.

**Comment by fissehab** [comment]
Hi, I am having the same error. So you said making the table name all in caps solved your problem. I tried with all caps but still I get the same error message.
